### ISSUE TITLE
Check why the logins don't work anymore

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#18]
Even before I moved the logins to login.c4dt.org, the stats stopped working.

**Comment by tharvik** [comment]
It seems that `cas-test` fails to connect to the `chromedriver`, something inside the agouti deps
> error: inject user: navigate to user injection page: failed to navigate: request unsuccessful: invalid session id

Anyone updated/changed something on `{conode,stats,switch}.c4dt.org` recently?

**Comment by cgrigis** [comment]
It stopped working on Sunday around 05:00 if I saw correctly... could it be a firewall issue with IC-IT?

**Comment by tharvik** [comment]
After some more investigation, I saw in the chromedriver logs
> [1615900863.671][SEVERE]: Unable to receive message from renderer

Which might happen for any number of reason. But I found a way to make it work (a bit better) (until the next version bump of chrome), see c4dt/omniledger#294

**Comment by tharvik** [comment]
> It stopped working on Sunday around 05:00 if I saw correctly... could it be a firewall issue with IC-IT?

It might be related, but as the `login.c4dt.org` chnages where merged before I can investigate, bah voilà hein.
