### ISSUE TITLE
clean /tmp/.org.chromium.* regularly

### ISSUE THREAD

**Issue by tharvik** [c4dt/stats#25]
A crontab/systemd entry erasing each dir older than a day would work.

**Comment by tharvik** [comment]
No need for it anymore. The upgrade to 20.04 fixes that by always using the same tmpdir for chromium.

**Comment by ineiti** [comment]
And the `tmp/onet`-directories are not too big?

**Comment by tharvik** [comment]
> And the `tmp/onet`-directories are not too big?

22K per dir, one dir per day, from what I remember.

Theses we can fix, removing the tempdir when done with it, but I don't know which cmd is generating it, do you have an idea?

**Comment by ineiti** [comment]
I suppose it's the `bcadmin db catchup`, but not sure.
