### ISSUE TITLE
website.wordpress and -www fails

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#27]
For some reason the website.wordpress and -www fails from time to time, and systemd decides to stop the timer.

Here is the last occurence:

```
journalctl -S "2021-09-26 22:08:02"
```

If I do the following, it works again:

```
stats@switch:~$ systemctl --user restart time-it-and-send-to-graphite@website.wordpress-www.loaded.service
stats@switch:~$ systemctl --user restart time-it-and-send-to-graphite@website.wordpress.loaded.service
```

**Comment by tharvik** [comment]
Yep, timer handling of systemd is not very well done, see https://github.com/systemd/systemd/issues/6680
That shouldn't happen but I don't think there is a better way to do it than restarting it manually, sadly..

**Comment by ineiti** [comment]
> That shouldn't happen but I don't think there is a better way to do it than restarting it manually, sadly..

That sounds like a good reason to drop the systemd-timer for collecting data...

But the issue you're linking to looks more like the timer never starting. Which is not the problem here. The timer starts, but when the `wget` fails, the timer is not called again. So perhaps a `|| true` or so to the `wget` could solve this problem?

**Comment by tharvik** [comment]
> > That shouldn't happen but I don't think there is a better way to do it than restarting it manually, sadly..
> 
> That sounds like a good reason to drop the systemd-timer for collecting data...

Feel free to find a better system and move to it, the infrastructure is cleanly separated.

> The timer starts, but when the `wget` fails, the timer is not called again. So perhaps a `|| true` or so to the `wget` could solve this problem?

That's not the case, the `journalctl` line you gave me clearly shows that `website.wordpress.loaded` and `website.wordpress-www.loaded` fail and then get restarted. It seems that `website.wordpress.loaded` then hangs until it is killed the next morning. I don't know the reason why as it was restarted, next time it fails, it would useful to have some more information such as the one found in `systemctl status time-it-and-send-to-graphite@website.wordpress.loaded.service`.

There is not much to be done here, I can't reproduce it and don't have information on what caused the hanging.

**Comment by ineiti** [comment]
OK, leaving this open until it fails again, then I'll run `systemctl status`...

**Comment by ineiti** [comment]
Didn't fail for nearly a year - closing.
