### ISSUE TITLE
Script takes lots of CPU and memory

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#32]
The following script takes a lot of CPU and memory on stats.c4dt.org:

/bin/sh -eu ./website.hits

I don't know why, though. `tail` on 50M lines? `egrep` with a complicated regex?

Anyway, I think it also impacts the conodes running on the server and might be part of the reason that the login is really slow now.

**Comment by tharvik** [comment]
right, it indeed takes a lot. I think that the memory footprint is mainly because I'm not handling streamingly..

I just found out that there was a `stream` option for `jq`, trying with that.

**Comment by tharvik** [comment]
* `jq` uses the most CPU
* `awk` uses the most memory (~20%)

I was able to greatly reduce both (at the expense of time) by simply piping `ssh` direclty into the stream.

**Comment by tharvik** [comment]
Haaha! Found what was the bottleneck: I'm starting a subprocess to translate date string to seconds since epoch. That does takes some time and ressources. Thankfully, `awk` does have time parsing capabilitities, moving to that makes it very fast :D
