### ISSUE TITLE
login checks fail

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#4]
With the new dynacred version, the login checks fail. I tried it, and the login works (at least for c4dt.org). But the status shows failures...

**Comment by tharvik** [comment]
concurrent login seems to be an issue, but I'm unable to reproduce locally, only on stats.c4dt.org.
the screenshot I got from the failure looks like it's hanging on "Loading user" when "Fetching latest block" from conode.dedis.ch; I'll investigate more.

**Comment by tharvik** [comment]
it seems to be working again, at least since 8AM, which correlate with the publication of a new [dynacred version](https://www.npmjs.com/package/@c4dt/dynacred/v/2.0.1-p20200602053230.0).

**Comment by tharvik** [comment]
looks like it is still working, closing.
