### ISSUE TITLE
Website hits not working anymore

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#41]
Uses ssh - need to find something else.

Simple idea - add webhook.c4dt.org with some endpoints:
- /stats - for getting the stats
- /ansible - for updating services, called by a github action

**Comment by tharvik** [comment]
No rush in doing it now, maybe a good first issue for Morgan?

**Comment by ineiti** [comment]
As a first it might be a bit long. But second or third...

**Comment by ineiti** [comment]
Also possible: Prometheus or OpenTelemetry

**Comment by tharvik** [comment]
https://docs.influxdata.com/telegraf/v1.24/ ?

**Comment by ineiti** [comment]
I like the telegraf solution, as it looks very minimal...

**Comment by tharvik** [comment]
fixed by https://github.com/c4dt/stats/pull/61
