### ISSUE TITLE
Alarm for c4dt.org

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#45]
We should put some reasonable alarms and alert our services@c4dt.org list or so:

- c4dt.org: 
  - working hours: > 5min
  - non-working hours: > 15min
- login matrix and wordpress: > 2h

**Comment by ineiti** [comment]
The current frequency of alerts makes it too noisy. I feel very important by all the notifications I get... And I just stopped them because they got too annoying. Which is not the goal.

So how much can you influence when an alert is being sent? Is something I wrote above possible, where alerts for the 'minor' services only get through when they're longer than 2h?

And alert for the 'c4dt.org' go through after 5 minutes?

**Comment by tharvik** [comment]
> The current frequency of alerts makes it too noisy.

Indeed, I hoped that there wasn't that much alert triggered in a night (or at least, that the current alerts weren't that much sensitive): look like I was wrong (:

> So how much can you influence when an alert is being sent?

We can set pretty much anything we want, see `dashboards-to-provision/common.py:simple_graph` for the definition.

https://github.com/c4dt/stats/pull/46 should take care of that

**Comment by ineiti** [comment]
OK, let's keep the issue open until we're satisfied with the frequency...

**Comment by ineiti** [comment]
Check BeVM failures which flood the alerts.

**Comment by ineiti** [comment]
Updated data/cothority/bc-*.cfg - BeVM OK, but now c4dt-login is complaining a lot.

**Comment by tharvik** [comment]
reduce freq for omniledger failling too much

**Comment by ineiti** [comment]
Let's close it for now. I'll reopen if it wakes me up during the week-ends :)
