### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#62]
Please add disk usage for all servers to the stats

**Comment by ineiti** [comment]
Where have all the server stats gone?

**Comment by PascalinDe** [comment]
@tharvik did indeed integrate these changes, but the webhook was not executed correctly

```
bash-5.0# cat logs/2023-04-03_145035_hooks.log 
Mon Apr  3 14:50:35 UTC 2023 Executing hook with repo c4dt/stats and event push
Cloning into '/deploy/ansible-config'...
Warning: Permanently added the ECDSA host key for IP address '140.82.121.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Running ansible with tag stats
ERROR! the playbook: /deploy/ansible-config/playbooks/main.yml could not be found
```

**Comment by PascalinDe** [comment]
so, the problem why the webhook was not executed correctly in April was that the public key it used to connect to GitHub was not good anymore (this we had fixed together)

than it had the same problem as https://github.com/c4dt/ansible-config/issues/154, so while waiting for your :+1: on the PR, I added the new public key manually and ran the ansible-playbook manually (from the webhook container)

I still see no server stats besides the stats for stats.c4dt.org itself, but at least the pipeline has been fixed now

**Comment by PascalinDe** [comment]
since the webhook is what checks out the Github repo, I had to pull @tharvik changes by hand, and force a rebuild of the dashboards, and now everything looks great: 
![Screenshot 2023-06-14 at 16-37-12 servers - Grafana](https://github.com/c4dt/stats/assets/15922677/3454bd96-e53b-4179-bb65-df5c5bdc6e33)

**Comment by PascalinDe** [comment]
normally the webhook should work fine now

**Comment by ineiti** [comment]
Close this?
