### ISSUE TITLE
Stats not loading

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#65]
- servers not loading
- matrix / tequila not showing

**Comment by PascalinDe** [comment]
![Screenshot 2023-06-19 at 14-16-13 servers - Grafana](https://github.com/c4dt/stats/assets/15922677/f622471f-5811-47c9-abdc-fed45b6d0091)

stats looks fine for me :confused:

**Comment by PascalinDe** [comment]
![Screenshot 2023-06-19 at 14-17-33 matrix - Grafana](https://github.com/c4dt/stats/assets/15922677/49777594-bb3c-4c60-a6bd-e4c49f29b82d)

**Comment by PascalinDe** [comment]
@lanterno confirms that it's working fine for him as well

**Comment by PascalinDe** [comment]
now it's not working anymore, so there seems to be a problem

there was a short downtime as well
![Screenshot 2023-06-19 at 16-08-07 Uptime Kuma](https://github.com/c4dt/stats/assets/15922677/90a0f03e-f0e5-49ef-81aa-cf0d063671a3)

**Comment by PascalinDe** [comment]
seems like the VM ran into some trouble around 15:44:

```
root@srv-switch-zh-1:~# dmesg -T | grep blocked
[Mon Jun 19 15:44:54 2023] INFO: task jbd2/vda1-8:265 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task traefik:5958 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task runsv:1024955 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task runsv:1024958 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task runsv:1024961 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task runsv:1024963 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task runsv:1024964 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task telegraf:234498 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task kworker/u2:2:399657 blocked for more than 120 seconds.
[Mon Jun 19 15:44:54 2023] INFO: task kworker/u2:4:422174 blocked for more than 120 seconds.
```

which is at the same time than the observed down time

**Comment by PascalinDe** [comment]
for the moment it seems to have returned and is working, I'll wait for the reboot tomorrow before looking closer

**Comment by PascalinDe** [comment]
no more blocked errors at least since the 21st

I updated telegraf just now, if there's no more problems until the end of the week I'll close this issue

**Comment by PascalinDe** [comment]
seems fine, no more issues, closing this
